In [1]:
import pandas as pd
import numpy as np
import math
import os
import tensorflow as tf

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

In [2]:
w1 = np.array([[1,2,3], [4,5,6], [7,8,9], [-1,-2,-3]])
w1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [-1, -2, -3]])

In [3]:
w1.shape

(4, 3)

In [4]:
a = np.array([[1], [1], [1]])
a

array([[1],
       [1],
       [1]])

In [5]:
a.shape

(3, 1)

In [6]:
b = np.dot(w1,a)

In [7]:
b

array([[ 6],
       [15],
       [24],
       [-6]])

In [8]:
c = np.dot([1, 0, 1, 0], b)
c

array([30])

In [9]:
df=pd.DataFrame(data=1, index=[0], columns=[i for i in range(59)], dtype=int) 
#df=pd.DataFrame()

In [10]:
df.shape

(1, 59)

In [11]:
df

0   1   2   3   4   5   6   7   8   9   ...  49  50  51  52  53  54  55  \
0   1   1   1   1   1   1   1   1   1   1  ...   1   1   1   1   1   1   1   

   56  57  58  
0   1   1   1  

[1 rows x 59 columns]

In [12]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(60, input_shape=(df.shape[1],), activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1, activation=tf.keras.activations.linear)
])

In [13]:
model.load_weights('weights.h5')

In [14]:
y_pred = model.predict(df)

In [15]:
y_pred

array([[1596.2369]], dtype=float32)