In [1]:
import numpy as np
mt=np.array([[1,2,3],[4,5,6]])

In [2]:
print(mt)

[[1 2 3]
 [4 5 6]]


In [5]:
print(mt.shape)

(2, 3)


In [6]:
print(f'{mt.shape=}')

mt.shape=(2, 3)


In [8]:
mt_r=mt.reshape([2,3,1])
print(mt_r)
print(f'{mt_r.shape=}')

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
mt_r.shape=(2, 3, 1)


In [12]:
print(np.zeros((2,3)))
print(np.ones((2,3,4), dtype=np.int32))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
