In [1]:
import numpy as np

In [2]:
Z=np.random.random((3,3))
print(Z)

[[0.23149841 0.13504674 0.68604124]
 [0.1779459  0.43998377 0.9851293 ]
 [0.79750435 0.98336367 0.20137931]]


In [3]:
Z[:,:]

array([[0.23149841, 0.13504674, 0.68604124],
       [0.1779459 , 0.43998377, 0.9851293 ],
       [0.79750435, 0.98336367, 0.20137931]])

In [4]:
Z[:,:-1]

array([[0.23149841, 0.13504674],
       [0.1779459 , 0.43998377],
       [0.79750435, 0.98336367]])

In [5]:
Z[:-1,:]

array([[0.23149841, 0.13504674, 0.68604124],
       [0.1779459 , 0.43998377, 0.9851293 ]])

In [6]:
Z[:,0]

array([0.23149841, 0.1779459 , 0.79750435])

In [7]:
Z[:,0:1]

array([[0.23149841],
       [0.1779459 ],
       [0.79750435]])

In [8]:
Z[:,0:2]

array([[0.23149841, 0.13504674],
       [0.1779459 , 0.43998377],
       [0.79750435, 0.98336367]])

In [9]:
import pandas as pd

In [10]:
df=pd.read_csv('train.csv')

In [11]:
df

id   timestamp  full_sq  life_sq  floor  max_floor  material  \
0          1  2011-08-20       43     27.0    4.0        NaN       NaN   
1          2  2011-08-23       34     19.0    3.0        NaN       NaN   
2          3  2011-08-27       43     29.0    2.0        NaN       NaN   
3          4  2011-09-01       89     50.0    9.0        NaN       NaN   
4          5  2011-09-05       77     77.0    4.0        NaN       NaN   
...      ...         ...      ...      ...    ...        ...       ...   
30466  30469  2015-06-30       44     27.0    7.0        9.0       1.0   
30467  30470  2015-06-30       86     59.0    3.0        9.0       2.0   
30468  30471  2015-06-30       45      NaN   10.0       20.0       1.0   
30469  30472  2015-06-30       64     32.0    5.0       15.0       1.0   
30470  30473  2015-06-30       43     28.0    1.0        9.0       1.0   

       build_year  num_room  kitch_sq  ...  cafe_count_5000_price_2500  \
0             NaN       NaN       NaN  ...                           9   
1             NaN       NaN       NaN  ...                          15   
2             NaN       NaN       NaN  ...                          10   
3             NaN       NaN       NaN  ...                          11   
4             NaN       NaN       NaN  ...                         319   
...           ...       ...       ...  ...                         ...   
30466      1975.0       2.0       6.0  ...                          15   
30467      1935.0       4.0      10.0  ...                         313   
30468         NaN       1.0       1.0  ...                           1   
30469      2003.0       2.0      11.0  ...                          22   
30470      1968.0       2.0       6.0  ...                           5   

      cafe_count_5000_price_4000 cafe_count_5000_price_high  \
0                              4                          0   
1                              3                          0   
2                              3                          0   
3                              2                          1   
4                            108                         17   
...                          ...                        ...   
30466                          5                          0   
30467                        128                         24   
30468                          1                          0   
30469                          1                          1   
30470                          2                          0   

       big_church_count_5000  church_count_5000  mosque_count_5000  \
0                         13                 22                  1   
1                         15                 29                  1   
2                         11                 27                  0   
3                          4                  4                  0   
4                        135                236                  2   
...                      ...                ...                ...   
30466                     15                 26                  1   
30467                     98                182                  1   
30468                      2                 12                  0   
30469                      6                 31                  1   
30470                      7                 16                  0   

       leisure_count_5000  sport_count_5000  market_count_5000  price_doc  
0                       0                52                  4    5850000  
1                      10                66                 14    6000000  
2                       4                67                 10    5700000  
3                       0                26                  3   13100000  
4                      91               195                 14   16331452  
...                   ...               ...                ...        ...  
30466                   2                84                  6    7400000  
30467                  82 

In [12]:
df.fillna(0, inplace=True)
df

id   timestamp  full_sq  life_sq  floor  max_floor  material  \
0          1  2011-08-20       43     27.0    4.0        0.0       0.0   
1          2  2011-08-23       34     19.0    3.0        0.0       0.0   
2          3  2011-08-27       43     29.0    2.0        0.0       0.0   
3          4  2011-09-01       89     50.0    9.0        0.0       0.0   
4          5  2011-09-05       77     77.0    4.0        0.0       0.0   
...      ...         ...      ...      ...    ...        ...       ...   
30466  30469  2015-06-30       44     27.0    7.0        9.0       1.0   
30467  30470  2015-06-30       86     59.0    3.0        9.0       2.0   
30468  30471  2015-06-30       45      0.0   10.0       20.0       1.0   
30469  30472  2015-06-30       64     32.0    5.0       15.0       1.0   
30470  30473  2015-06-30       43     28.0    1.0        9.0       1.0   

       build_year  num_room  kitch_sq  ...  cafe_count_5000_price_2500  \
0             0.0       0.0       0.0  ...                           9   
1             0.0       0.0       0.0  ...                          15   
2             0.0       0.0       0.0  ...                          10   
3             0.0       0.0       0.0  ...                          11   
4             0.0       0.0       0.0  ...                         319   
...           ...       ...       ...  ...                         ...   
30466      1975.0       2.0       6.0  ...                          15   
30467      1935.0       4.0      10.0  ...                         313   
30468         0.0       1.0       1.0  ...                           1   
30469      2003.0       2.0      11.0  ...                          22   
30470      1968.0       2.0       6.0  ...                           5   

      cafe_count_5000_price_4000 cafe_count_5000_price_high  \
0                              4                          0   
1                              3                          0   
2                              3                          0   
3                              2                          1   
4                            108                         17   
...                          ...                        ...   
30466                          5                          0   
30467                        128                         24   
30468                          1                          0   
30469                          1                          1   
30470                          2                          0   

       big_church_count_5000  church_count_5000  mosque_count_5000  \
0                         13                 22                  1   
1                         15                 29                  1   
2                         11                 27                  0   
3                          4                  4                  0   
4                        135                236                  2   
...                      ...                ...                ...   
30466                     15                 26                  1   
30467                     98                182                  1   
30468                      2                 12                  0   
30469                      6                 31                  1   
30470                      7                 16                  0   

       leisure_count_5000  sport_count_5000  market_count_5000  price_doc  
0                       0                52                  4    5850000  
1                      10                66                 14    6000000  
2                       4                67                 10    5700000  
3                       0                26                  3   13100000  
4                      91               195                 14   16331452  
...                   ...               ...                ...        ...  
30466                   2                84                  6    7400000  
30467                  82 

In [13]:
columns=['price_doc','timestamp','full_sq','life_sq','floor','max_floor','material','build_year','num_room','kitch_sq','state','product_type','sub_area']

In [14]:
df=df[columns]

In [15]:
df

price_doc   timestamp  full_sq  life_sq  floor  max_floor  material  \
0        5850000  2011-08-20       43     27.0    4.0        0.0       0.0   
1        6000000  2011-08-23       34     19.0    3.0        0.0       0.0   
2        5700000  2011-08-27       43     29.0    2.0        0.0       0.0   
3       13100000  2011-09-01       89     50.0    9.0        0.0       0.0   
4       16331452  2011-09-05       77     77.0    4.0        0.0       0.0   
...          ...         ...      ...      ...    ...        ...       ...   
30466    7400000  2015-06-30       44     27.0    7.0        9.0       1.0   
30467   25000000  2015-06-30       86     59.0    3.0        9.0       2.0   
30468    6970959  2015-06-30       45      0.0   10.0       20.0       1.0   
30469   13500000  2015-06-30       64     32.0    5.0       15.0       1.0   
30470    5600000  2015-06-30       43     28.0    1.0        9.0       1.0   

       build_year  num_room  kitch_sq  state   product_type  \
0             0.0       0.0       0.0    0.0     Investment   
1             0.0       0.0       0.0    0.0     Investment   
2             0.0       0.0       0.0    0.0     Investment   
3             0.0       0.0       0.0    0.0     Investment   
4             0.0       0.0       0.0    0.0     Investment   
...           ...       ...       ...    ...            ...   
30466      1975.0       2.0       6.0    3.0     Investment   
30467      1935.0       4.0      10.0    3.0     Investment   
30468         0.0       1.0       1.0    1.0  OwnerOccupier   
30469      2003.0       2.0      11.0    2.0     Investment   
30470      1968.0       2.0       6.0    2.0     Investment   

                   sub_area  
0                  Bibirevo  
1         Nagatinskij Zaton  
2            Tekstil'shhiki  
3                    Mitino  
4                 Basmannoe  
...                     ...  
30466              Otradnoe  
30467              Tverskoe  
30468  Poselenie Vnukovskoe  
30469          Obruchevskoe  
30470           Novogireevo  

[30471 rows x 13 columns]

In [16]:
df.dtypes

price_doc         int64
timestamp        object
full_sq           int64
life_sq         float64
floor           float64
max_floor       float64
material        float64
build_year      float64
num_room        float64
kitch_sq        float64
state           float64
product_type     object
sub_area         object
dtype: object

In [17]:
df=df._get_numeric_data()
df.head()

price_doc  full_sq  life_sq  floor  max_floor  material  build_year  \
0    5850000       43     27.0    4.0        0.0       0.0         0.0   
1    6000000       34     19.0    3.0        0.0       0.0         0.0   
2    5700000       43     29.0    2.0        0.0       0.0         0.0   
3   13100000       89     50.0    9.0        0.0       0.0         0.0   
4   16331452       77     77.0    4.0        0.0       0.0         0.0   

   num_room  kitch_sq  state  
0       0.0       0.0    0.0  
1       0.0       0.0    0.0  
2       0.0       0.0    0.0  
3       0.0       0.0    0.0  
4       0.0       0.0    0.0

In [18]:
df_test=df.sample(n=1000, random_state=0)
df_train=df.drop(index=df_test.index)

df_test=df_test.reset_index(drop=True)
df_train=df_train.reset_index(drop=True)

In [19]:
df_train.columns[1:]
#Показать все колонки кроме первой

Index(['full_sq', 'life_sq', 'floor', 'max_floor', 'material', 'build_year',
       'num_room', 'kitch_sq', 'state'],
      dtype='object')

In [20]:
x_train=df_train[df_train.columns[1:]]
y_train=df_train['price_doc']

x_test=df_test[df_test.columns[1:]]
y_test=df_test['price_doc']

In [21]:
from sklearn.metrics import mean_squared_log_error

In [22]:
y_predicted=y_train.median()

In [23]:
predictions=np.array([y_train.median()]*1000)

In [24]:
print(f'Значение метрики при предсказании медианой: {np.sqrt(mean_squared_log_error(y_test, predictions))}')

Значение метрики при предсказании медианой: 0.6043387231257158


In [25]:
baseline=np.sqrt(mean_squared_log_error(y_test, predictions))

In [26]:
from sklearn import preprocessing

min_max = preprocessing.MinMaxScaler()
standard = preprocessing.StandardScaler()

min_max.fit(x_train)
standard.fit(x_train)

x_train_min_max=min_max.transform(x_train)
x_test_min_max=min_max.transform(x_test)

x_train_standard=standard.transform(x_train)
x_test_standard=standard.transform(x_test)

In [27]:
import sklearn.linear_model as lm

In [28]:
linear_regression=lm.LinearRegression().fit(X=x_train_min_max, y=y_train)

In [34]:
def calculate_metric(x_train, x_test, y_train, y_test, model):
    
    predictions_test=model.predict(x_test)
    predictions_train=model.predict(x_train)
    
    if (predictions_test<0).any() or (predictions_train<0).any():
        predictions_test[np.where(predictions_test<0)]=0
        predictions_train[np.where(predictions_train<0)]=0
    
    metric_test=np.sqrt(mean_squared_log_error(y_test, predictions_test))
    metric_train=np.sqrt(mean_squared_log_error(y_train, predictions_train))
    
    delta_baseline=baseline-metric_test
    
    print(f"Значение метрики RMSLE на тесте : {metric_test}")
    print(f"Значение метрики RMSLE на трейне: {metric_train}")
    print(f"Улучшение метрики по сравнению с бейзлайонм: {delta_baseline}")
    return metric_test

In [35]:
calculate_metric(x_train_min_max, x_test_min_max, y_train, y_test, linear_regression)

Значение метрики RMSLE на тесте : 0.6290325545472407
Значение метрики RMSLE на трейне: 0.6296628165855316
Улучшение метрики по сравнению с бейзлайонм: -0.024693831421524925


0.6290325545472407

In [36]:
linear_regression=lm.LinearRegression().fit(X=x_train_standard, y=y_train)

In [37]:
mt=calculate_metric(x_train_standard, x_test_standard, y_train, y_test, linear_regression)

Значение метрики RMSLE на тесте : 0.5588000012725928
Значение метрики RMSLE на трейне: 0.5571633028324688
Улучшение метрики по сравнению с бейзлайонм: 0.04553872185312302


In [38]:
print(round(mt,2))

0.56


In [39]:
for c in df.columns[1:]:
    df[c+'_2']=df[c]*df[c]
    df[c+'_3']=df[c+'_2']*df[c]
    df[c+'_4']=df[c+'_3']*df[c]

In [40]:
df

price_doc  full_sq  life_sq  floor  max_floor  material  build_year  \
0        5850000       43     27.0    4.0        0.0       0.0         0.0   
1        6000000       34     19.0    3.0        0.0       0.0         0.0   
2        5700000       43     29.0    2.0        0.0       0.0         0.0   
3       13100000       89     50.0    9.0        0.0       0.0         0.0   
4       16331452       77     77.0    4.0        0.0       0.0         0.0   
...          ...      ...      ...    ...        ...       ...         ...   
30466    7400000       44     27.0    7.0        9.0       1.0      1975.0   
30467   25000000       86     59.0    3.0        9.0       2.0      1935.0   
30468    6970959       45      0.0   10.0       20.0       1.0         0.0   
30469   13500000       64     32.0    5.0       15.0       1.0      2003.0   
30470    5600000       43     28.0    1.0        9.0       1.0      1968.0   

       num_room  kitch_sq  state  ...  build_year_4  num_room_2  num_room_3  \
0           0.0       0.0    0.0  ...  0.000000e+00         0.0         0.0   
1           0.0       0.0    0.0  ...  0.000000e+00         0.0         0.0   
2           0.0       0.0    0.0  ...  0.000000e+00         0.0         0.0   
3           0.0       0.0    0.0  ...  0.000000e+00         0.0         0.0   
4           0.0       0.0    0.0  ...  0.000000e+00         0.0         0.0   
...         ...       ...    ...  ...           ...         ...         ...   
30466       2.0       6.0    3.0  ...  1.521488e+13         4.0         8.0   
30467       4.0      10.0    3.0  ...  1.401922e+13        16.0        64.0   
30468       1.0       1.0    1.0  ...  0.000000e+00         1.0         1.0   
30469       2.0      11.0    2.0  ...  1.609622e+13         4.0         8.0   
30470       2.0       6.0    2.0  ...  1.500031e+13         4.0         8.0   

       num_room_4  kitch_sq_2  kitch_sq_3  kitch_sq_4  state_2  state_3  \
0             0.0         0.0         0.0         0.0      0.0      0.0   
1             0.0         0.0         0.0         0.0      0.0      0.0   
2             0.0         0.0         0.0         0.0      0.0      0.0   
3             0.0         0.0         0.0         0.0      0.0      0.0   
4             0.0         0.0         0.0         0.0      0.0      0.0   
...           ...         ...         ...         ...      ...      ...   
30466        16.0        36.0       216.0      1296.0      9.0     27.0   
30467       256.0       100.0      1000.0     10000.0      9.0     27.0   
30468         1.0         1.0         1.0         1.0      1.0      1.0   
30469        16.0       121.0      1331.0     14641.0      4.0      8.0   
30470        16.0        36.0       216.0      1296.0      4.0      8.0   

       state_4  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0  
...        ...  
30466     81.0  
30467     81.0  
30468      1.0  
30469     16.0  
30470     16.0  

[30471 rows x 37 columns]

In [41]:
df_test=df.sample(n=1000, random_state=0)
df_train=df.drop(index=df_test.index)

df_test=df_test.reset_index(drop=True)
df_train=df_train.reset_index(drop=True)

In [42]:
x_train=df_train[df_train.columns[1:]]
y_train=df_train['price_doc']

x_test=df_test[df_test.columns[1:]]
y_test=df_test['price_doc']

In [43]:
min_max = preprocessing.MinMaxScaler()
standard = preprocessing.StandardScaler()

min_max.fit(x_train)
standard.fit(x_train)

x_train_min_max=min_max.transform(x_train)
x_test_min_max=min_max.transform(x_test)

x_train_standard=standard.transform(x_train)
x_test_standard=standard.transform(x_test)

In [44]:
linear_regression=lm.LinearRegression().fit(X=x_train_min_max, y=y_train)

In [45]:
calculate_metric(x_train_min_max, x_test_min_max, y_train, y_test, linear_regression)

Значение метрики RMSLE на тесте : 0.5304738348291971
Значение метрики RMSLE на трейне: 0.6539447023274371
Улучшение метрики по сравнению с бейзлайонм: 0.07386488829651872


0.5304738348291971

In [46]:
ridge=lm.Ridge().fit(X=x_train_min_max, y=y_train)

In [47]:
calculate_metric(x_train_min_max, x_test_min_max, y_train, y_test, ridge)

Значение метрики RMSLE на тесте : 0.5543492717965633
Значение метрики RMSLE на трейне: 0.5544899453593606
Улучшение метрики по сравнению с бейзлайонм: 0.049989451329152446


0.5543492717965633

In [48]:
lasso=lm.Lasso().fit(X=x_train_min_max, y=y_train)

C:\Users\Vadim\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.962e+17, tolerance: 6.758e+13
  model = cd_fast.enet_coordinate_descent(


In [49]:
calculate_metric(x_train_min_max, x_test_min_max, y_train, y_test, lasso)

Значение метрики RMSLE на тесте : 0.5319535894961515
Значение метрики RMSLE на трейне: 0.6350687703682347
Улучшение метрики по сравнению с бейзлайонм: 0.07238513362956434


0.5319535894961515

In [50]:
lasso.coef_

array([ 6.22401778e+08,  1.31568236e+08,  2.71346600e+07, -7.95184390e+06,
        1.34154014e+07,  5.18419989e+07, -5.21375384e+07,  9.61586419e+07,
       -1.39049183e+07, -2.87108759e+09,  1.92015296e+09,  3.34766758e+08,
       -6.05228253e+08,  4.27324306e+08,  4.47471270e+07, -2.05669305e+08,
        5.80973924e+08, -3.97068900e+08,  4.84943576e+07, -4.59641077e+07,
        3.61028717e+06, -1.17485593e+07, -7.57612300e+06,  7.58772577e+06,
       -6.50542142e+07, -1.33396047e+04, -1.29060647e+00,  3.39996596e+08,
       -3.46360563e+08,  4.85909020e+07, -3.03212204e+08,  1.59945468e+08,
        4.63036689e+07,  3.38538869e+08, -2.04933028e+08, -1.02187348e+08])

In [55]:
df.columns

Index(['price_doc', 'full_sq', 'life_sq', 'floor', 'max_floor', 'material',
       'build_year', 'num_room', 'kitch_sq', 'state', 'full_sq_2', 'full_sq_3',
       'full_sq_4', 'life_sq_2', 'life_sq_3', 'life_sq_4', 'floor_2',
       'floor_3', 'floor_4', 'max_floor_2', 'max_floor_3', 'max_floor_4',
       'material_2', 'material_3', 'material_4', 'build_year_2',
       'build_year_3', 'build_year_4', 'num_room_2', 'num_room_3',
       'num_room_4', 'kitch_sq_2', 'kitch_sq_3', 'kitch_sq_4', 'state_2',
       'state_3', 'state_4'],
      dtype='object')